Repository softeerbootcamp4th/fe-newsstand, pull requests merged in 2024-07, with the labels that each got.

#91 [0708] 김지민 - 구독 기능 구현
  components/main.js
  components/modal.js
  components/toastAlert.js
  data/allNews.json
  index.html
  js/category.js
  js/loadComponent.js
  js/mainTab.js
  js/subscribe.js
  modal.styles.css
  src/icons/chevron-right.svg
  src/images/boyKoreaNews.png
  styles.css
Labels: enhancement, HTML

#100 [성락현] 팝업 기능 추가 및 버그수정
  .DS_Store
  README.md
  index.css
  index.html
  json/articleDataList.js
  json/articles.js
  json/companies.js
  main.js
  pages/new.html
  scripts/addEventToRotatingArrow.js
  scripts/addEventToToggle.js
  scripts/article.js
  scripts/company.js
  scripts/fetchData.js
  scripts/getCurrentDateString.js
  scripts/initialize.js
  scripts/magicNumber.js
  scripts/popup.js
  scripts/render.js
  scripts/subscribe.js
  scripts/swiper.js
  scripts/tab.js
  scripts/toggle.js
  scripts/util.js
  style/news.css
Labels: bug, enhancement

#106 [7/8] 박지현 - 구현 상황
  components/displaynews/displayNews.js
  components/displaynews/displaysubscribe.js
  components/mainscript.js
  components/stand.html
  components/subscribe/subalarm.js
  components/subscribe/subscribe.js
  components/testing/progressbutton.js
  css/globalfonts.css
  css/test.css
  icons/chevron-right.svg
  image/MBC.svg
  image/국민일보.svg
  image/뉴스데일리.svg
  image/뉴스타파.svg
  image/일간스포츠.svg
  image/코리아헤럴드.svg
  news/allnews.json
Labels: bug, enhancement

#110 [이태혁] FEAT: 구독해지 기능, Toast UI 구현
  components/fieldTab/fieldTab.js
  components/news/allNews/allNews.js
  components/news/subscriptionNews/subscriptionNews.js
  components/subscribe/addSubscribe.js
  components/subscribe/removeSubscribtion.js
  components/subscription/addSubscription.js
  components/subscription/isSubscribe.js
  components/subscription/removeSubscription.js
  components/subscription/renderSubscriptionBtn.js
  components/subscription/style.css
  components/subscriptionSwitchBtn/style.css
  components/subscriptionSwitchBtn/subscriptionSwitchBtn.js
  components/swipe/allSwipe.js
  components/swipe/subscriptionSwipe.js
  components/toast/renderToast.js
  components/toast/style.css
  data/brandData.js
  data/cateData.js
  index.html
  index.js
  style.css
  style/common.css
  util/getSubscribeList.js
Labels: feature

#111 [성락현] API 연동 및 코드 리펙토링
  index.html
  json/articleDataList.js
  main.js
  scripts/addEventToRotatingBox.js
  scripts/drag.js
  scripts/fetchData.js
  scripts/initialize.js
  scripts/popup.js
  scripts/render.js
  scripts/rolling.js
  scripts/subscribe.js
  scripts/swiper.js
  style/news.css
Labels: bug, enhancement

#114 [0709] 김지민 - 구독 기능 마무리, 롤링배너 리팩토링, 그리드 뷰 구현
  components/main.js
  index.html
  js/app.js
  js/gridView.js
  js/iconTab.js
  js/listView.js
  js/mainTab.js
  js/rollingnews.js
  js/subscribe.js
  styles.css
Labels: HTML, feature

#124 [7/9 조민환] 뉴스 카테고리 클릭 시 해당하는 뉴스 데이터 동적 생성 및 프로그래스바 애니메이션 구현, 뉴스 카테고리 프로그래스바 자동 반복 구현, UI 수정
  asset/data/newsData.json
  asset/images/LG엔솔.jpg
  asset/images/ai.png
  asset/images/yoon.jpg
  asset/images/기사사진1.svg
  asset/images/김민재.jpg
  asset/images/연두색 번호판.jpg
  asset/images/충청권 폭우.jpg
  css/styles.css
  index.html
  js/loadNewsData.js
  js/navTheme.js
Labels: HTML, feature

#127 [ 박대원 ] useEffect 구현 && 구독 Alert && useState 구조가 변동됨에 따른 리팩토링
  newsstand/src/App.js
  newsstand/src/components/base/Alert.js
  newsstand/src/components/base/Button.js
  newsstand/src/components/category/CategoryBox.js
  newsstand/src/components/category/CategoryText.js
  newsstand/src/components/category/MediaCategories.js
  newsstand/src/components/news/MainNews.js
  newsstand/src/components/news/NewsBox.js
  newsstand/src/core/hooks/useEffect.js
  newsstand/src/core/hooks/useState.js
  newsstand/src/layouts/news-container/GridNewsstand.js
  newsstand/src/layouts/news-container/ListNewsstand.js
  newsstand/src/layouts/news-container/NewsContainer.js
  newsstand/src/layouts/source-selector/NewsSourceSelector.js
  newsstand/src/utils/subscribeUtils.js
  newsstand/styles/base/Alert.css
  newsstand/styles/index.css
  newsstand/styles/layout.css
Labels: feature

#132 [성락현] Refactor
  index.html
  json/articleDataList.js
  main.js
  scripts/article.js
  scripts/company.js
  scripts/fetchData.js
  scripts/magicNumber.js
  scripts/render.js
  scripts/rolling.js
  scripts/subscribe.js
  scripts/swiper.js
  scripts/tab.js
  scripts/toggle.js
  scripts/util.js
Labels: bug, invalid

#136 [0710] 김지민 - feat : grid view 구독 기능 구현, 구독 언론사 데이터 연동, 리스트뷰와 그리드뷰 이동시 현재 탭 유지 구현
  components/main.js
  js/app.js
  js/displaygridViewnews.js
  js/displaylistViewNews.js
  js/gridView.js
  js/iconTab.js
  js/initialGridView.js
  js/mainTab.js
  js/subscribe.js
  js/toggleView.js
  styles.css
Labels: HTML, feature

#138 [ 박대원 ] Toast, Alert 구현 및 코드 리팩토링
  newsstand/src/App.js
  newsstand/src/components/base/Alert.js
  newsstand/src/components/base/Button.js
  newsstand/src/components/base/IconView.js
  newsstand/src/components/base/Toast.js
  newsstand/src/components/category/CategoryBox.js
  newsstand/src/components/category/CategoryText.js
  newsstand/src/components/category/MediaCategories.js
  newsstand/src/components/news/MainNews.js
  newsstand/src/components/news/NewsBox.js
  newsstand/src/core/hooks/useState.js
  newsstand/src/layouts/news-container/GridNewsstand.js
  newsstand/src/layouts/news-container/ListNewsstand.js
  newsstand/src/layouts/news-container/NewsContainer.js
  newsstand/src/layouts/sub-header/SubHeader.js
  newsstand/src/utils/listUtils.js
  newsstand/src/utils/subscribeUtils.js
  newsstand/src/utils/toastUtils.js
  newsstand/styles/base/Alert.css
  newsstand/styles/base/Toast.css
  newsstand/styles/index.css
Labels: HTML, feature

#145 [7/10 조민환] 프로그래스바 애니메이션이 다음 카테고리로 넘어갈 때 그에 해당하는 뉴스 데이터 동적 생성 구현
  asset/data/newsData.json
  asset/images/bloter 메인 썸네일.jpg
  asset/images/bloter.svg
  asset/images/korea joongang daily 메인 썸네일.jpg
  asset/images/korea joongang daily.svg
  asset/images/mbc 메인 썸네일.jpg
  asset/images/mbc.svg
  asset/images/obs 메인 썸네일.jpg
  asset/images/obs.svg
  asset/images/서울신문 메인 썸네일.jpg
  asset/images/서울신문.svg
  asset/images/소년한국일보 메인 썸네일.jpg
  asset/images/소년한국일보.svg
  asset/images/일간스포츠 메인 썸네일.jpg
  asset/images/일간스포츠.svg
  css/styles.css
  index.html
  js/loadNewsData.js
  js/navTheme.js
  js/newsLoaderWithProgress.js
Labels: feature

#149 [7/10] 박지현 애니메이션 적용 완료
  components/displaynews/displayNews.js
  components/displaynews/displaysubscribe.js
  components/mainscript.js
  components/newstab/newstab.js
  components/newstab/progressbutton.js
  components/newstab/sub.js
  components/newstab/test.css
  components/newstab/test.html
  components/progressbar/progressbutton.js
  css/test.css
  news/allnews.json
Labels: documentation

#164 [장승호] 07/11 PR
  data/company.json
  data/news.json
  img/10.png
  img/7.png
  img/8.png
  img/9.png
  img/danger.png
  index.html
  src/grid.js
  src/index.js
  src/news.js
  src/util.js
  style/index.css
Labels: feature

#165 [7/11 조민환] 뉴스 카테고리 프로그래스바 애니메이션 구현
  asset/data/newsData.json
  asset/images/경향신문 메인 썸네일.jpg
  asset/images/경향신문.svg
  asset/images/디지털타임스 메인 썸네일.jpg
  asset/images/디지털타임스.svg
  css/styles.css
  index.html
  js/newsLoaderWithProgress.js
  js/reloadPage.js
Labels: enhancement, HTML, feature

#166 [7/11] 박지현 구현 상황
  components/Home.js
  components/displaynews/displayNews.js
  components/displaynews/displaysubscribe.js
  components/fetch.js
  components/mainscript.js
  components/newstab/newstab.js
  components/newstab/sub.html
  components/progressbar/progressbutton.js
  components/stand.html
  components/statemanager/stateManager.js
  components/statemanager/subscribeManager.js
  components/subscribe/subalarm.js
  components/subscribe/subscribe.js
  css/Home.css
  css/test.css
Labels: documentation

#171 [성락현] store 리팩토링
  main.js
  scripts/article.js
  scripts/company.js
  scripts/drag.js
  scripts/initialize.js
  scripts/popup.js
  scripts/render.js
  scripts/reset.js
  scripts/rolling.js
  scripts/store.js
  scripts/subscribe.js
  scripts/swiper.js
  scripts/tab.js
  scripts/toggle.js
  style/news.css
Labels: bug, enhancement
